language: java
install: true


dist: trusty
jdk:
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
    -master
    -v7.6.0
    

script:
  - ./gradlew build --scan -s