language: java
install: true


dist: trusty
jdk:
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea
    

script:
  - ./gradlew build --scan -s -x oldEs2Fixture -x oldEs1Fixture -x oldEs090Fixture